# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        
      - name: Build solution
        run: dotnet build --configuration Release
        
      - name: Pack and publish NuGet packages
        shell: pwsh
        env:
          HWNDEXTENSIONS_NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          .NuGet\nuget-pack.ps1
          .NuGet\nuget-publish.ps1
